### PR TITLE
Add Google Loaders

### PR DESCRIPTION
**Pull request by 8bitgentleman**
Adds in two loaders based on Google's material design

### CODE REVIEW

**Comment by joaomgcd** [comment]
Thanks for the pull request! :) Did these work correctly for you?

**Comment by 8bitgentleman** [comment]
I'm not sure how to test web screens with multiple files but if everything is in one HTML file it works. Is there a way to test multiple files or should I  put each loader in one html file?

**Comment by joaomgcd** [comment]
To test:

- Add the new loading screen type to the "loadingType" AutoTools variable in page.html
- name the new loading screen files the same as the loading type you added but with no spaces and all lowercase
- make sure you have this new version on your android device, select the new type and see how it looks :) It automatically loads the files needed.

Let me know if you can get it to work, thanks!

**Comment by 8bitgentleman** [comment]
Sorry I keep asking questions but I'm still a little unclear on the process to test this. I'm running v1.0.26b which I assume is the newest version.  I've pushed the changes to my branch so what file do I put under the web screen source?

**Comment by joaomgcd** [comment]
Ok, sorry I fixed it myself :) There was a bug in the main page that didn't allow this to be tested properly.

Also, I forgot to mention that the root element in the loading type has to have an id that's the same as the file name :)

All in all, this is all fixed now and they look great :D Thanks for adding them!

**Pull request merged**
